version: '3'
services:
  db_bloggy:
    image: mysql:latest
    restart: always
    command: --max_allowed_packet=2G
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      
    volumes:
      - mysql-bloggy:/var/lib/mysql
    networks:
      - mysql-network
    ports:
      - '3306:3306'
    expose:
      - '3306'

  db_bloggynews:
    image: mysql:latest
    restart: always
    command: --max_allowed_packet=2G
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_TCP_PORT=3307
    volumes:
      - mysql-bloggynews:/var/lib/mysql
    networks:
      - mysql-network
    ports:
      - '3307:3307'
    expose:
      - '3307'

  db_subscribed:
    
    image: mysql:latest
    restart: always
    command: --max_allowed_packet=2G
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_TCP_PORT=3308
    volumes:
      - mysql-subscribed:/var/lib/mysql
    networks:
      - mysql-network
    ports:
      - '3308:3308'
    expose:
      - '3308'

  db_notsubscribed:
    
    image: mysql:latest
    restart: always
    command: --max_allowed_packet=2G
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_TCP_PORT=3309
    volumes:
      - mysql-notsubscribed:/var/lib/mysql
    networks:
      - mysql-network
    ports:
      - '3309:3309'
    expose:
      - '3309'

 

  app:
    build:
     
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - mysql-network
    depends_on:
      - db_bloggy
      - db_bloggynews
      - db_subscribed
      - db_notsubscribed
networks:
  mysql-network:
    driver: bridge
volumes:
  mysql-bloggy:
  mysql-bloggynews:
  mysql-subscribed:
  mysql-notsubscribed:
